// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using productservice.Data;
using System;

namespace productservice.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20171108131007_CorrectionOnProductModel")]
    partial class CorrectionOnProductModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("productservice.Model.Product", b =>
                {
                    b.Property<int>("productId")
                        .ValueGeneratedOnAdd();

                    b.Property<int[]>("childrenProductsIds")
                        .HasColumnName("childrenProductsIds")
                        .HasColumnType("integer[]");

                    b.Property<bool>("enabled");

                    b.Property<int?>("parentProducId");

                    b.Property<string>("producCode")
                        .HasMaxLength(50);

                    b.Property<string>("producDescription")
                        .HasMaxLength(100);

                    b.Property<string>("producName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("productGTIN")
                        .HasMaxLength(50);

                    b.HasKey("productId");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
